import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Card } from '../components/Card'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Practice at implementing Next.js & Typescript!
          </h1>

          <div className={styles.grid}>
            <Card
              title="Typescript"
              href="#"
              content="Practice for implementing Typescript"
            />
            <Card
              title="GraphQL"
              href="#"
              content="Practice for implementing Graph QL"
            />
            <Card
              title="Material-UI"
              href="#"
              content="See Material-UI user experience"
            />
            <Card title="Jest" href="#" content="See Jest working its magic" />
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="hhttps://utum.co.nz"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/favicon.ico"
                alt="UTUM Ltd Logo"
                width={25}
                height={50}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}

export default Home
